name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build web app
        env:
          VITE_APP_URL: ${{ vars.VITE_APP_URL }}
        run: "deno task build:web"

      - name: Deploy API to Deno Deploy
        uses: denoland/deployctl@v1

        with:
          project: "zaber-api"
          entrypoint: "apps/api/index.ts"
          include: apps/api/**
          exclude: node_modules

      - name: Deploy Web to Deno Deploy
        uses: denoland/deployctl@v1

        with:
          project: "zaber"
          entrypoint: "apps/web/server.ts"
          include: apps/web/**, packages/**
          exclude: node_modules
